from django.contrib.auth import logout
from django.urls import path
from . import views

urlpatterns=[
    path('',views.home,name='home'),
    path('home',views.home,name='home'),
    path('homemsg',views.homemsg,name='homemsg'),
    path('userl',views.userl,name='userl'),
    path('userdashboard',views.userdashboard,name='userdashboard'),
    path('uevent',views.uevent,name='uevent'),
    path('logout',views.logout,name='logout'),
    path('upast',views.upast,name='upast'),
    path('ubookdetail',views.ubookdetail,name='ubookdetail'),
    path('editbook/<int:id>',views.editbook,name='editbook'),
    path('updatebook/<int:id>',views.updatebook,name='updatebook'),
    path('uprofile',views.uprofile,name='uprofile'),
    path('uedit/<int:id>',views.uedit,name='uedit'),
    path('uchangepass/<int:id>',views.uchangepass,name='uchangepass'),
    path('updateprofile/<int:id>',views.updateprofile,name='updateprofile'),
    path('deleteprofile/<int:id>',views.deleteprofile,name='deleteprofile'),
    path('upurchase',views.upurchase,name='upurchase'),
    path('adminavailable',views.adminavailable,name='adminavailable'),
    path('Bankpayment',views.Bankpayment,name='Bankpayment'),
    path('paymentsuccess',views.paymentsuccess,name='paymentsuccess'),
    path("eimage",views.eimage,name='eimage'),
    path('storyfeed',views.storyfeed,name='storyfeed'),
    path('users',views.users,name='users'),
    path('admlog',views.admlog,name='admlog'),
    path('admsign',views.admsign,name='admsign'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('adevent',views.adevent,name='adevent'),
    path('adManageEvent',views.adManageEvent,name='adManageEvent'),
    path('adbookedit/<int:id>',views.adbookedit,name='adbookedit'),
    path('updateadbook/<int:id>',views.updateadbook,name='updateadbook'),
    path('deleteadbook/<int:id>',views.deleteadbook,name='deleteadbook'),
    path('adTotal',views.adTotal,name='adTotal'),
    path('adminPast',views.adminPast,name='adminPast'),
    path('BookingDetails',views.BookingDetails,name='BookingDetails'),
    path('manualedit/<int:id>',views.manualedit,name='manualedit'),
    path('manualupdate/<int:id>',views.manualupdate,name='manualupdate'),
    path('adminmanual',views.adminmanual,name='adminmanual'),
    path('adminProfile',views.adminProfile,name='adminProfile'),
    path('editprofile/<int:id>',views.editprofile,name='editprofile'),
    path('adminchangepassword/<int:id>',views.adminchangepassword,name='adminchangepassword'),
    path('updateadminpass/<int:id>',views.updateadminpass,name='updateadminpass'),
    path('DeleteadPass/<int:id>',views.DeleteadPass,name='DeleteadPass'),
    path('adminadduser',views.adminadduser,name='adminadduser'),
    path('adminmanageuser',views.adminmanageuser,name='adminmanageuser'),
    path('editmanager/<int:id>',views.editmanager,name='editmanager'),
    path('manageupdate/<int:id>',views.manageupdate,name='manageupdate'),
    path('managedlt/<int:id>',views.managedlt,name='managedlt'),
    path('ship',views.ship,name='ship'),
    path('Manageship',views.Manageship,name='Manageship'),
    path('shipform/<int:id>',views.shipform,name='shipform'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('Planrequest',views.Planrequest,name='Planrequest'),
    path('planedit/<int:id>',views.planedit,name='planedit'),
    path('planupdate/<int:id>',views.planupdate,name='planupdate'),
    path('PAYEVENT',views.PAYEVENT,name='PAYEVENT'),
    path('adminContactus',views.adminContactus,name='adminContactus'),
    path('contactusedit/<int:id>',views.contactusedit,name='contactusedit'),
    path('adminContactmanage',views.adminContactmanage,name='adminContactmanage'),
    path('admineditprofile/<int:id>',views.admineditprofile,name='admineditprofile'),
    path('EditProfile/<int:id>',views.EditProfile,name='EditProfile'),

    
    
]