# Generated by Django 3.2.3 on 2021-06-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('passwrd', models.CharField(max_length=32)),
                ('rpass', models.CharField(max_length=32)),
            ],
        ),
    ]
