# Generated by Django 3.2.3 on 2021-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_usign'),
    ]

    operations = [
        migrations.CreateModel(
            name='asign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=32)),
                ('password2', models.CharField(max_length=32)),
            ],
        ),
    ]
