# Generated by Django 3.2.3 on 2021-06-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_asign'),
    ]

    operations = [
        migrations.CreateModel(
            name='uaddevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('ans', models.CharField(max_length=12)),
                ('maximum', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('amount', models.CharField(max_length=10000000)),
                ('content', models.CharField(max_length=100000)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('service', models.CharField(max_length=500)),
                ('utube', models.URLField()),
            ],
        ),
    ]
