# Generated by Django 3.2.3 on 2021-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_uaddevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uaddevent',
            name='date',
            field=models.DateField(verbose_name='%Y:%m:%d;%H:%M'),
        ),
    ]
