# Generated by Django 3.2.3 on 2021-06-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_alter_uaddevent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='proedituser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userp', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
