# Generated by Django 3.2.3 on 2021-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_proedituser'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usern', models.CharField(max_length=40)),
                ('uGender', models.CharField(max_length=12)),
                ('homead', models.CharField(max_length=100)),
                ('eid', models.CharField(max_length=50)),
                ('phnum', models.CharField(max_length=11)),
            ],
        ),
    ]
