# Generated by Django 3.2.3 on 2021-06-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='membership',
        ),
    ]
