# Generated by Django 3.2.3 on 2021-06-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_delete_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='myprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=100)),
                ('mygender', models.CharField(max_length=12)),
                ('myaddress', models.CharField(max_length=200)),
                ('myemail', models.EmailField(max_length=254)),
                ('myphn', models.CharField(max_length=15)),
            ],
        ),
    ]
