# Generated by Django 3.2.3 on 2021-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_myprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='adevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeventname', models.CharField(max_length=100)),
                ('adate', models.DateField()),
                ('acategorize', models.CharField(max_length=12)),
                ('nomembers', models.CharField(max_length=1000)),
                ('atime', models.TimeField()),
                ('amountperone', models.CharField(max_length=100000)),
                ('adescription', models.CharField(max_length=1000)),
                ('Aaddress', models.CharField(max_length=10000)),
                ('aimage', models.ImageField(blank=True, null=True, upload_to='aimage')),
                ('aservices', models.CharField(max_length=100)),
                ('youtube', models.URLField()),
            ],
        ),
    ]
