# Generated by Django 3.2.3 on 2021-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_adevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adevents',
            name='Aaddress',
            field=models.CharField(max_length=500),
        ),
    ]
