# Generated by Django 3.2.3 on 2021-06-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_alter_adevents_aaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaddevent',
            old_name='eventname',
            new_name='aeventname',
        ),
    ]
