# Generated by Django 3.2.3 on 2021-06-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_rename_eventname_uaddevent_aeventname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaddevent',
            old_name='address',
            new_name='Aaddress',
        ),
        migrations.RenameField(
            model_name='uaddevent',
            old_name='ans',
            new_name='acategorize',
        ),
        migrations.RenameField(
            model_name='uaddevent',
            old_name='date',
            new_name='adate',
        ),
        migrations.RenameField(
            model_name='uaddevent',
            old_name='content',
            new_name='adescription',
        ),
        migrations.RenameField(
            model_name='uaddevent',
            old_name='amount',
            new_name='amountperone',
        ),
        migrations.RenameField(
            model_name='uaddevent',
            old_name='service',
            new_name='aservices',
        ),
        migrations.RenameField(
            model_name='uaddevent',
            old_name='time',
            new_name='atime',
        ),
        migrations.RenameField(
            model_name='uaddevent',
            old_name='maximum',
            new_name='nomembers',
        ),
        migrations.RenameField(
            model_name='uaddevent',
            old_name='utube',
            new_name='youtube',
        ),
        migrations.RemoveField(
            model_name='uaddevent',
            name='image',
        ),
        migrations.AddField(
            model_name='uaddevent',
            name='aimage',
            field=models.ImageField(blank=True, null=True, upload_to='aimage'),
        ),
    ]
