# Generated by Django 3.2.3 on 2021-06-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0015_manualbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameofuser', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=100)),
                ('Planname', models.CharField(max_length=12)),
                ('verification', models.CharField(max_length=2)),
            ],
        ),
    ]
