# Generated by Django 3.2.3 on 2021-06-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0016_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactEmail', models.EmailField(max_length=254)),
                ('showemail', models.CharField(max_length=2)),
                ('contactphone', models.CharField(max_length=15)),
                ('showcontact', models.CharField(max_length=15)),
                ('contactAddress', models.CharField(max_length=100)),
                ('showaddress', models.CharField(max_length=100)),
                ('sendemail', models.CharField(max_length=2)),
                ('showdatabase', models.CharField(max_length=2)),
            ],
        ),
    ]
