# Generated by Django 3.2.3 on 2021-06-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0018_admincontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='admembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=100)),
                ('plantype', models.CharField(max_length=100)),
                ('planprice', models.CharField(max_length=100)),
                ('planstatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminContact',
        ),
    ]
