# Generated by Django 3.2.3 on 2021-06-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0019_auto_20210624_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admembership',
        ),
    ]
