# Generated by Django 3.2.3 on 2021-06-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0020_delete_admembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAMEofPLAN', models.CharField(max_length=50)),
                ('PlanType', models.CharField(max_length=20)),
                ('PlanPrice', models.CharField(max_length=12)),
                ('PlanStatus', models.CharField(max_length=2)),
            ],
        ),
    ]
