# Generated by Django 3.2.3 on 2021-06-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0022_alter_adminuser_planname'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('cardowner', models.CharField(max_length=100)),
            ],
        ),
    ]
