# Generated by Django 3.2.3 on 2021-07-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0023_paymentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmembership',
            name='PlanPrice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addmembership',
            name='PlanStatus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addmembership',
            name='PlanType',
            field=models.CharField(max_length=100),
        ),
    ]
